name: Upload to S3

on:
  push:
    branches:
      - main  # Change this if you're using a different branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Replace with your bucket's region

      - name: Upload files to S3
        run: |
          aws s3 cp . s3://taxi-data-testing1/ --recursive --exclude ".git/" --exclude ".github/"
